settings:
    number_of_replicas: 0
    number_of_shards: 1
    refresh_interval: 60s
mappings:
    dynamic: false
    properties:
        code:
            type: keyword
        sku:
            type: keyword
        name:
            type: text
            #analyzer: english
            fields:
                autocomplete:
                    type: text
                    analyzer: app_autocomplete
                    search_analyzer: standard
        enabled:
            type: boolean
        createdAt:
            type: date
        updatedAt:
            type: date
        image:
            #type: keyword
            enabled: false
        parent:
            type: keyword
        slugs:
            type: keyword
        category:
            type: object
            properties:
                name:
                    type: text
                    analyzer: english
                slug:
                    type: keyword
                enabled:
                    type: boolean
                id:
                    type: keyword
                parent:
                    type: keyword
                tree:
                    type: keyword
                left:
                    type: integer
                right:
                    type: integer
                level:
                    type: integer
        values:
            type: object
            properties:
                #name:
                #    type: text
                picture:
                    #type: keyword
                    enabled: false
                power_requirements:
                    type: keyword
                associations:
                    enabled: false
                #field_1:
                #    type: string

